# Site settings
title: Philip's Notebook
email: Phillysoul11@gmail.com
description: "Online residence of Philip C Davis"
baseurl: ""
url: "http://philipcdavis.com"
exclude: ['node_modules']

# Build settings
markdown: kramdown
permalink: notebook/:title
